In [1]:
import pandas as pd

optical = pd.read_csv('/content/cleaned_satellite_dataset.csv')

sar = pd.read_csv('/content/AgriAstra_Sentinel1.csv')

In [2]:
sar.head()

,system:index,VH,VV,.geo
0,0,-20.025476,-12.354627,"{""type"":""Point"",""coordinates"":[79.221722504579..."
1,1,-17.326365,-9.763876,"{""type"":""Point"",""coordinates"":[79.310390943453..."
2,2,-18.558639,-11.072210,"{""type"":""Point"",""coordinates"":[79.347911246388..."
3,3,-19.862415,-10.367734,"{""type"":""Point"",""coordinates"":[79.296441849472..."
4,4,-19.174761,-12.459310,"{""type"":""Point"",""coordinates"":[79.262416130511..."

In [3]:
sar.columns

Index(['system:index', 'VH', 'VV', '.geo'], dtype='object')

In [4]:
optical = optical.drop(columns=['.geo'])

sar = sar.drop(columns=['system:index', '.geo'])

optical.head()

sar.head()

          VH         VV
0 -20.025476 -12.354627
1 -17.326365  -9.763876
2 -18.558639 -11.072210
3 -19.862415 -10.367734
4 -19.174761 -12.459310

In [5]:
print(optical.shape)

print(sar.shape)

(500, 2)
(500, 2)

In [6]:
master_df = pd.concat([optical, sar], axis=1)

master_df.head()

       NDVI      NDWI         VH         VV
0  0.348767 -0.476177 -20.025476 -12.354627
1  0.641812 -0.498966 -17.326365  -9.763876
2  0.826490 -0.700789 -18.558639 -11.072210
3  0.778754 -0.679737 -19.862415 -10.367734
4  0.401090 -0.466092 -19.174761 -12.459310

In [7]:
master_df.columns

Index(['NDVI', 'NDWI', 'VH', 'VV'], dtype='object')

In [8]:
master_df.to_csv(
'merged_satellite_dataset.csv',
index=False
)

print("Master dataset created.")

Master dataset created.

In [9]:
master_df.head()

       NDVI      NDWI         VH         VV
0  0.348767 -0.476177 -20.025476 -12.354627
1  0.641812 -0.498966 -17.326365  -9.763876
2  0.826490 -0.700789 -18.558639 -11.072210
3  0.778754 -0.679737 -19.862415 -10.367734
4  0.401090 -0.466092 -19.174761 -12.459310

In [10]:
master_df.shape

(500, 4)