In [1]:
import pandas as pd

df = pd.read_csv('/content/final_agriastra_dataset.csv')

df.head()

       NDVI      NDWI         VH         VV   Rainfall
0  0.348767 -0.476177 -20.025476 -12.354627  18.531933
1  0.641812 -0.498966 -17.326365  -9.763876  18.531933
2  0.826490 -0.700789 -18.558639 -11.072210  18.531933
3  0.778754 -0.679737 -19.862415 -10.367734  18.531933
4  0.401090 -0.466092 -19.174761 -12.459310  18.531933

In [2]:
df.shape

(500, 5)

In [3]:
df.columns

Index(['NDVI', 'NDWI', 'VH', 'VV', 'Rainfall'], dtype='object')

In [4]:
df.describe()

             NDVI        NDWI          VH          VV      Rainfall
count  500.000000  500.000000  500.000000  500.000000  5.000000e+02
mean     0.511452   -0.507637  -18.895526  -11.501738  1.853193e+01
std      0.267414    0.211502    3.060490    2.822817  2.204888e-13
min     -0.541726   -0.777235  -35.844577  -27.581717  1.853193e+01
25%      0.277854   -0.669441  -20.002540  -12.497561  1.853193e+01
50%      0.524586   -0.538030  -18.556364  -11.338676  1.853193e+01
75%      0.776746   -0.408049  -17.256731  -10.217962  1.853193e+01
max      0.878077    0.688162  -10.337940   -3.528195  1.853193e+01

In [5]:
def classify_stress(row):

    if row['NDWI'] < -0.6:
        return 'High'

    elif row['NDWI'] < -0.3:
        return 'Moderate'

    else:
        return 'Low'


df['Moisture_Stress'] = df.apply(
    classify_stress,
    axis=1
)

df.head()

       NDVI      NDWI         VH         VV   Rainfall Moisture_Stress
0  0.348767 -0.476177 -20.025476 -12.354627  18.531933        Moderate
1  0.641812 -0.498966 -17.326365  -9.763876  18.531933        Moderate
2  0.826490 -0.700789 -18.558639 -11.072210  18.531933            High
3  0.778754 -0.679737 -19.862415 -10.367734  18.531933            High
4  0.401090 -0.466092 -19.174761 -12.459310  18.531933        Moderate

In [6]:
df['Moisture_Stress'].value_counts()

Moisture_Stress
Moderate    257
High        196
Low          47
Name: count, dtype: int64

In [7]:
df.to_csv(
    'agriastra_ai_dataset.csv',
    index=False
)

print("AI dataset ready.")

AI dataset ready.